import * as React from 'react';
import * as UnisIcons from '../../src';

function App() {
  return (
    <div className="max-w-sm m-auto p-4 flex flex-wrap text-gray-900">
      <UnisIcons.AppWindow />
      <UnisIcons.Backspace />
      <UnisIcons.BatteryCharging />
      <UnisIcons.BatteryChargingVertical />
      <UnisIcons.BatteryEmpty />
      <UnisIcons.BatteryFull />
      <UnisIcons.BatteryHigh />
      <UnisIcons.BatteryLow />
      <UnisIcons.BatteryMedium />
      <UnisIcons.BatteryPlus />
      <UnisIcons.BatteryWarning />
      <UnisIcons.BatteryWarningVertical />
      <UnisIcons.Bell />
      <UnisIcons.BellRinging />
      <UnisIcons.BellSimple />
      <UnisIcons.BellSimpleRinging />
      <UnisIcons.BellSimpleSlash />
      <UnisIcons.BellSimpleZ />
      <UnisIcons.BellSlash />
      <UnisIcons.BellZ />
      <UnisIcons.Bluetooth />
      <UnisIcons.BluetoothConnected />
      <UnisIcons.BluetoothSlash />
      <UnisIcons.BluetoothX />
      <UnisIcons.Browser />
      <UnisIcons.Browsers />
      <UnisIcons.CellSignalFull />
      <UnisIcons.CellSignalHigh />
      <UnisIcons.CellSignalLow />
      <UnisIcons.CellSignalMedium />
      <UnisIcons.CellSignalNone />
      <UnisIcons.CellSignalSlash />
      <UnisIcons.CellSignalX />
      <UnisIcons.Check />
      <UnisIcons.CheckCircle />
      <UnisIcons.CheckSquare />
      <UnisIcons.CheckSquareOffset />
      <UnisIcons.Checks />
      <UnisIcons.CloudArrowDown />
      <UnisIcons.CloudArrowUp />
      <UnisIcons.CloudCheck />
      <UnisIcons.CloudSlash />
      <UnisIcons.Command />
      <UnisIcons.ComputerTower />
      <UnisIcons.Cursor />
      <UnisIcons.Desktop />
      <UnisIcons.DesktopTower />
      <UnisIcons.DeviceMobile />
      <UnisIcons.DeviceMobileCamera />
      <UnisIcons.DeviceMobileSpeaker />
      <UnisIcons.DeviceTablet />
      <UnisIcons.DeviceTabletCamera />
      <UnisIcons.DeviceTabletSpeaker />
      <UnisIcons.DotsNine />
      <UnisIcons.DotsSix />
      <UnisIcons.DotsSixVertical />
      <UnisIcons.DotsThree />
      <UnisIcons.DotsThreeCircle />
      <UnisIcons.DotsThreeCircleVertical />
      <UnisIcons.DotsThreeOutline />
      <UnisIcons.DotsThreeOutlineVertical />
      <UnisIcons.DotsThreeVertical />
      <UnisIcons.Download />
      <UnisIcons.DownloadSimple />
      <UnisIcons.Flashlight />
      <UnisIcons.Gauge />
      <UnisIcons.Gear />
      <UnisIcons.GearSix />
      <UnisIcons.HamburgerMenu />
      <UnisIcons.HardDrive />
      <UnisIcons.HardDrives />
      <UnisIcons.KeyReturn />
      <UnisIcons.Keyboard />
      <UnisIcons.Laptop />
      <UnisIcons.Lightbulb />
      <UnisIcons.LightbulbFilament />
      <UnisIcons.Lightning />
      <UnisIcons.LightningSlash />
      <UnisIcons.Link />
      <UnisIcons.LinkBreak />
      <UnisIcons.LinkSimple />
      <UnisIcons.LinkSimpleBreak />
      <UnisIcons.LinkSimpleHorizontal />
      <UnisIcons.LinkSimpleHorizontalBreak />
      <UnisIcons.MagnifyingGlass />
      <UnisIcons.MagnifyingGlassMinus />
      <UnisIcons.MagnifyingGlassPlus />
      <UnisIcons.Monitor />
      <UnisIcons.MonitorPlay />
      <UnisIcons.Mouse />
      <UnisIcons.MouseSimple />
      <UnisIcons.Notification />
      <UnisIcons.Nut />
      <UnisIcons.Option />
      <UnisIcons.Plug />
      <UnisIcons.Plugs />
      <UnisIcons.PlugsConnected />
      <UnisIcons.Power />
      <UnisIcons.QrCode />
      <UnisIcons.RadioButton />
      <UnisIcons.Scan />
      <UnisIcons.SignIn />
      <UnisIcons.SignOut />
      <UnisIcons.SimCard />
      <UnisIcons.Spinner />
      <UnisIcons.SpinnerGap />
      <UnisIcons.Swap />
      <UnisIcons.Tabs />
      <UnisIcons.ToggleLeft />
      <UnisIcons.ToggleRight />
      <UnisIcons.Upload />
      <UnisIcons.UploadSimple />
      <UnisIcons.Vibrate />
      <UnisIcons.WifiHigh />
      <UnisIcons.WifiLow />
      <UnisIcons.WifiMedium />
      <UnisIcons.WifiNone />
      <UnisIcons.WifiSlash />
      <UnisIcons.WifiX />
      <UnisIcons.Wrench />
    </div>
  );
}

export default App;
