import * as React from 'react';
import * as UnisIcons from '../../src';

function App() {
  return (
    <div className="max-w-sm m-auto p-4 flex flex-wrap text-gray-900">
      <UnisIcons.Archive />
      <UnisIcons.ArchiveBox />
      <UnisIcons.ArchiveTray />
      <UnisIcons.Briefcase />
      <UnisIcons.BriefcaseMetal />
      <UnisIcons.Cards />
      <UnisIcons.Clipboard />
      <UnisIcons.ClipboardText />
      <UnisIcons.Copy />
      <UnisIcons.CopySimple />
      <UnisIcons.CursorText />
      <UnisIcons.File />
      <UnisIcons.FileArrowDown />
      <UnisIcons.FileArrowUp />
      <UnisIcons.FileAudio />
      <UnisIcons.FileCloud />
      <UnisIcons.FileCode />
      <UnisIcons.FileCss />
      <UnisIcons.FileCsv />
      <UnisIcons.FileDoc />
      <UnisIcons.FileDotted />
      <UnisIcons.FileHtml />
      <UnisIcons.FileImage />
      <UnisIcons.FileJpg />
      <UnisIcons.FileJs />
      <UnisIcons.FileJsx />
      <UnisIcons.FileLock />
      <UnisIcons.FileMinus />
      <UnisIcons.FilePdf />
      <UnisIcons.FilePlus />
      <UnisIcons.FilePng />
      <UnisIcons.FilePpt />
      <UnisIcons.FileRs />
      <UnisIcons.FileSearch />
      <UnisIcons.FileText />
      <UnisIcons.FileTs />
      <UnisIcons.FileTsx />
      <UnisIcons.FileVideo />
      <UnisIcons.FileVue />
      <UnisIcons.FileX />
      <UnisIcons.FileXls />
      <UnisIcons.FileZip />
      <UnisIcons.Files />
      <UnisIcons.FloppyDisk />
      <UnisIcons.FloppyDiskBack />
      <UnisIcons.Folder />
      <UnisIcons.FolderDotted />
      <UnisIcons.FolderLock />
      <UnisIcons.FolderMinus />
      <UnisIcons.FolderNotch />
      <UnisIcons.FolderNotchMinus />
      <UnisIcons.FolderNotchOpen />
      <UnisIcons.FolderNotchPlus />
      <UnisIcons.FolderOpen />
      <UnisIcons.FolderPlus />
      <UnisIcons.FolderSimple />
      <UnisIcons.FolderSimpleDotted />
      <UnisIcons.FolderSimpleLock />
      <UnisIcons.FolderSimpleMinus />
      <UnisIcons.FolderSimplePlus />
      <UnisIcons.FolderSimpleStar />
      <UnisIcons.FolderSimpleUser />
      <UnisIcons.FolderStar />
      <UnisIcons.FolderUser />
      <UnisIcons.Folders />
      <UnisIcons.Funnel />
      <UnisIcons.FunnelSimple />
      <UnisIcons.Kanban />
      <UnisIcons.List />
      <UnisIcons.ListBullets />
      <UnisIcons.ListChecks />
      <UnisIcons.ListDashes />
      <UnisIcons.ListNumbers />
      <UnisIcons.ListPlus />
      <UnisIcons.Note />
      <UnisIcons.NoteBlank />
      <UnisIcons.NotePencil />
      <UnisIcons.Notebook />
      <UnisIcons.Notepad />
      <UnisIcons.Paperclip />
      <UnisIcons.PaperclipHorizontal />
      <UnisIcons.Presentation />
      <UnisIcons.PresentationChart />
      <UnisIcons.Printer />
      <UnisIcons.ProjectorScreen />
      <UnisIcons.ProjectorScreenChart />
      <UnisIcons.PushPin />
      <UnisIcons.PushPinSimple />
      <UnisIcons.PushPinSimpleSlash />
      <UnisIcons.PushPinSlash />
      <UnisIcons.SortAscending />
      <UnisIcons.SortDescending />
      <UnisIcons.TextAa />
      <UnisIcons.TextAlignCenter />
      <UnisIcons.TextAlignJustify />
      <UnisIcons.TextAlignLeft />
      <UnisIcons.TextAlignRight />
      <UnisIcons.TextBolder />
      <UnisIcons.TextH />
      <UnisIcons.TextHFive />
      <UnisIcons.TextHFour />
      <UnisIcons.TextHOne />
      <UnisIcons.TextHSix />
      <UnisIcons.TextHThree />
      <UnisIcons.TextHTwo />
      <UnisIcons.TextIndent />
      <UnisIcons.TextItalic />
      <UnisIcons.TextOutdent />
      <UnisIcons.TextStrikethrough />
      <UnisIcons.TextT />
      <UnisIcons.TextUnderline />
      <UnisIcons.Textbox />
      <UnisIcons.Trash />
      <UnisIcons.TrashSimple />
      <UnisIcons.Tray />
    </div>
  );
}

export default App;
