name: website
on:
  release:
    types: [created, published]
jobs:
  website:
    name: Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 'lts/*'
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Building
        run: yarn website:build
